### ISSUE TITLE
Install Signal-P

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/metagenomics_summer_school#30]
@JSBoey Can you remind why we need this again ?. Sorry you did explain it to me during the meeting but I didn't catch the whole story

**Comment by JSBoey** [comment]
Signal-P 6.0 is software that predicts signal peptides regardless of taxonomy. Earlier versions of this software requires the user to know in advance the Gram stain status of the organism, which can be inherently difficult for novel, non-culture genomes. I thought it might be useful to point out to the learners in case they need that information but you correctly pointed out that there is a license attached depending on the user.

**Comment by DininduSenanayake** [comment]
@JSBoey This is done but I don't have a test case to verify whether all the functions are working. Can you try and let me know please ?

```
$ module load SignalP/6.0g-gimkl-2022a-Python-3.10.5

$ signalp6 --help
usage: SignalP 6.0 Signal peptide prediction tool [-h] --fastafile FASTAFILE --output_dir OUTPUT_DIR
                                                  [--format [{txt,png,eps,all,none}]] [--organism [{eukarya,other,euk}]]
                                                  [--mode [{fast,slow,slow-sequential}]] [--bsize BSIZE]
                                                  [--write_procs WRITE_PROCS] [--version] [--skip_resolve]


```

**Comment by JSBoey** [comment]
I tried running it: 
```sh
module load SignalP/6.0g-gimkl-2022a-Python-3.10.5

signalp6 -ff predictions/bin_0.filtered.genes.no_metadata.faa -od test_signalp/bin_0 --write_procs 2
```
However, I think the model files are missing?
```sh
ValueError: The provided filename /opt/nesi/CS400_centos7_bdw/SignalP/6.0g-gimkl-2022a-Python-3.10.5/lib/python3.10/site-packages/signalp/model_weights/distilled_model_signalp6.pt does not exist
```

I tried with all model options: `fast`, `slow`, `slow-sequential` but none worked. Did the authors provide the models files?

**Comment by DininduSenanayake** [comment]
@JSBoey Ah...This is what I wasn't sure of. It didn't carry over the models to the correct path during the build. I have manually copied them to `model_weights` directory now. Can you try again and confirm the status ?

**Comment by JSBoey** [comment]
@DininduSenanayake Yay, it works! Perfect, thank you!
