### ISSUE TITLE
Update viral processing steps to VirSorter2 and DRAM-v

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#31]
MH to update viral processing steps to remove `VIBRANT` and replace with `VirSorter2` and `DRAM-v.py`. These are currently the most often used programs for these jobs, and will also more closely parallel with the prokaryote bin processing steps (which are being annotated via `DRAM.py`).

**Comment by DininduSenanayake** [comment]
@mlhoggard Just confirming that we are **not** going to use `VIBRANT` then. If yes, I will not update it to be compatible with *Python/3.10.5* and leave the existing *VIBRANT/1.2.1-gimkl-2020a* as it is

**Comment by mlhoggard** [comment]
@DininduSenanayake  Yeah, to confirm, *not* using `VIBRANT` this year (we still use it in our own research though) so you can leave it as is! And will instead incorporate `VirSorter/2.2.3-gimkl-2020a-Python-3.8.2 ` and `DRAM-v.py` (from `DRAM` module).
