### ISSUE TITLE
MaxBin missing libraries in milan but not in large

### ISSUE THREAD

**Issue by JSBoey** [GenomicsAotearoa/metagenomics_summer_school#36]
This is the error message if `partition=milan` is used in the slurm script:

```
Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /opt/nesi/CS400_centos7_bdw/MaxBin/2.2.7-GCC-11.3.0-Perl-5.34.1/run_MaxBin.pl line 4.
BEGIN failed--compilation aborted at /opt/nesi/CS400_centos7_bdw/MaxBin/2.2.7-GCC-11.3.0-Perl-5.34.1/run_MaxBin.pl line 4.
```

This error does not show up if using partitions other than large (essentially omitting `partition=milan` from the script).

**Comment by DininduSenanayake** [comment]
Thanks @JSBoey Not the missing library error I was expecting but still pointing to the differences in operating system as both old and new os has system Perl and there are differences with respect to which perl extensions are available by default. 

I can fix this by adding the missing Perl extension to Maxbin module. This is the better solution anyway as it is a bit more future proof ( In case we update the operating system again)

**Comment by DininduSenanayake** [comment]
@JSBoey I have made bit of a mess of this. Adding the Perl extension which `milan` was complaining about ended up breaking the whole module. In other words, it is not working anywhere now. Given the time constraint, I am going to undo the change and get it to work on non-milan partitions and update the slurm script to reflect that

**Comment by JSBoey** [comment]
All good. This will be an addition of partition into the SBATCH I presume? Will you need to manually divert the jobs on the day?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DininduSenanayake** [comment]
Let's delete the `#SBATCH --partition` variable altogether from that script. This way it will go to non-milan reserved nodes by default

**Comment by DininduSenanayake** [comment]
This is fixed now and Maxbin can run on `milan`. I just ran the same dataset we use on MGSS

```bash
49279521        maxbin_clusteri+    10    00:00:47    01:51.766     10G          COMPLETED  
49279521.batch  batch               10    00:00:47    01:51.765           79380K COMPLETED  
49279521.extern extern              10    00:00:47    00:00.001                0 COMPLETED  
```
```
$ sacct -j 49279521  --format=partition
 Partition 
---------- 
     milan 
```
```bash
$ tree -L 1 maxbin
maxbin
├── maxbin.001.fasta
├── maxbin.002.fasta
├── maxbin.003.fasta
├── maxbin.004.fasta
├── maxbin.005.fasta
├── maxbin.006.fasta
├── maxbin.007.fasta
├── maxbin.008.fasta
├── maxbin.009.fasta
├── maxbin.010.fasta
├── maxbin.log
├── maxbin.marker
├── maxbin.marker_of_each_bin.tar.gz
├── maxbin.noclass
├── maxbin.summary
└── maxbin.tooshort
```
```bash
$ tail maxbin_clustering_49279521.out 
Summary file: maxbin/maxbin.summary
Marker counts: maxbin/maxbin.marker
Marker genes for each bin: maxbin/maxbin.marker_of_each_gene.tar.gz
Bin files: maxbin/maxbin.001.fasta - maxbin/maxbin.010.fasta
Unbinned sequences: maxbin/maxbin.noclass


========== Elapsed Time ==========
0 hours 0 minutes and 40 seconds.
````
