### ISSUE TITLE
DIAMOND/2.1.9-GCC-11.3.0 doesn't run in array

### ISSUE THREAD

**Issue by JSBoey** [GenomicsAotearoa/metagenomics_summer_school#53]
Shared library not loaded properly. Error message: `diamond: error while loading shared libraries: liblmdb.so: cannot open shared object file: No such file or directory`

**Comment by DininduSenanayake** [comment]
* Confirming `liblmdb.so` is linked `diamond` binary 

```bash
$  ldd /opt/nesi/CS400_centos7_bdw/DIAMOND/2.1.9-GCC-11.3.0/bin/diamond  | grep "liblmdb"

	liblmdb.so => /lib64/liblmdb.so (0x00002aaaaacfb000)
```
* Proposed fix to rebuild DIAMOND module with `LMDB` as a dependency. Making sure the missing shared object file is coming from `LMDB` module itself 

```bash
$ ls /opt/nesi/CS400_centos7_bdw/LMDB/0.9.29-GCC-11.3.0/lib  
liblmdb.a  liblmdb.so
```

This should be solved now as LMDB gets loaded alongside DIAMOND module

```bash
$ module load DIAMOND/2.1.9-GCC-11.3.0 

$ module list | grep LMDB
  1) XALT/minimal   2) slurm   3) NeSI (S)   4) GCCcore/11.3.0   5) zlib/1.2.11-GCCcore-11.3.0   6) binutils/2.38-GCCcore-11.3.0   7) GCC/11.3.0   **8) LMDB/0.9.29-GCC-11.3.0**   9) DIAMOND/2.1.9-GCC-11.3.0
````

@JSBoey Can you try again and confirm the status ?

**Comment by JSBoey** [comment]
Thanks @DininduSenanayake. The module now works as an array job and all 10 jobs completed. I will close this.
