### ISSUE TITLE
3 - Assembly I

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#62]
Defunct link on "swap space". 

See line: "Memory limit to prevent the assembler from using up all available RAM and forcing the computer to use its [swap space](https://web.mit.edu/rhel-doc/5/RHEL-5-manual/Deployment_Guide-en-US/ch-swapspace.html)"

**Comment by kmhandley** [comment]
Could link to this page instead: https://www.geeksforgeeks.org/swap-space-in-operating-system/

**Comment by JSBoey** [comment]
Redirected link to suggested page
