### ISSUE TITLE
3 - Assembly II

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#64]
All good, except I suggest adding the following line after "Make a few copies of your initial slurm scripts and tweak a few of the assembly parameters.": 

"Make sure to also change the assembly output file (e.g. from spades_assembly to spades_assembly_var1)."

**Comment by kmhandley** [comment]
Ah I see this is noted at the bottom of the page under "Outputs per variant job", but I think that could come sooner, or a note where indicated above to check the below for important information.

**Comment by JSBoey** [comment]
Agree with bringing the heads up sooner and have added the suggested text.
