### ISSUE TITLE
4 - Assembly evaluation

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#65]
I suggest deleting the Limitations box. Because 16S is highly conserved, EMIRGE is pretty good at recovering novel sequences. 

Also there are other options for taxa identification available that take into account novelty based on metagenomic data, e.g. GTDB-Tk classification of MAGs.

**Comment by kmhandley** [comment]
PS That is delete the limitations box under "Reconstruct rRNA using PhyloFlash-EMIRGE".

Also, in the text above change "16S" to "16S and 18S"

**Comment by JSBoey** [comment]
Box removed and added 16S and 18S to text
