### ISSUE TITLE
4 - Assembly evaluation (part 2)

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#66]
Everything ran well. For metaquast, as viewing affects more than just the report.html file, it may be helpful for the entire output directory to be compressed and then downloaded. 

Add this line of code after the sbatch script or to the end of the sbatch script: 

**tar -cvzf metaquast_results.tar.gz metaquast_results**

Then in the Viewing HTML in Jupyter Hub box change the text from "To view a basic version of the report, download the report file by navigating to the 4.evaluation/metaquast_results/ folder, right-click report.html/ and select download." to "To view a basic version of the report, download the report file by navigating to the 4.evaluation/metaquast_results.tar.gz/ folder, right-click and select download."

**Comment by JSBoey** [comment]
Added archiving and download instructions
