### ISSUE TITLE
Manual bin refinement script correction

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#68]
Script here needs correction: 

https://genomicsaotearoa.github.io/metagenomics_summer_school/day2/ex9_refining_bins/#prepare-files-for-vizbin

It includes `cat ${i} >> all_mock_bins.fna` but there's no `i` variable defined earlier in the script. Should this be `cat ${bin}`?

**Comment by mlhoggard** [comment]
Also in the same script, it first refers to ` all_mock_bins.label.txt` then in the script appends to ` all_mock_bins.label.ann` (i.e. suffix changes)

**Comment by mlhoggard** [comment]
Also worth adding info to right click in VizBin and click `legend` to be able to tell the labels for each coloured bin (i.e. since we suggest they label their new clusters based on this)

**Comment by kmhandley** [comment]
Yes, update as follows (as indicated by Mike). This works, and add suggestion by Mike to add legend.

# VizBin requires a header for annotation files
echo "label" > all_mock_bins.label.ann

# Generate concatenated set of sequences and labels at the same time!
for bin in mock_bins/*.fna; do
    binID=$(basename ${bin} .fna)
    grep '>' ${bin} | sed "s/.*/${binID}/g" >> all_mock_bins.label.ann
    cat ${bin} >> all_mock_bins.fna
done

**Comment by JSBoey** [comment]
Fixed typos
