### ISSUE TITLE
Viral taxonomy tax_predict file missing

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#70]
In viral taxonomy prediction section, we've provided the vConTACT2 output files rather than getting them to run it. But the file `vConTACT2_Results/tax_predict_table.tsv` (the output from `tax_predict_vConTACT2_0.9.19.py`) is missing.

Section: https://genomicsaotearoa.github.io/metagenomics_summer_school/day3/ex10.2_viruses/#introduction-to-vcontact2-for-predicting-taxonomy-of-viral-contigs

**Comment by JSBoey** [comment]
- Pushed `tax_predict_table.tsv` to `7.viruses/vConTACT2_Results`
- Add `tax_predict_vConTACT2_0.9.19.py` to `7.viruses/`
- Modifies appendix page to reflect correct location for `tax_predict_table.tsv`
