### ISSUE TITLE
Viral taxonomy cytoscape session, missing `Dataset` column

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#71]
Regenerated vConTACT2 output needs `Dataset` column manually added to `genome_by_genome_overview.csv` (column header `Dataset`, entries `Our_data` (rows with 'NODE') or `RefSeq` (all other rows).

**Comment by JSBoey** [comment]
Added `Dataset` column and pushed to `starter_files`
