### ISSUE TITLE
Gene prediction, prodigal mode mismatch

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#72]
https://genomicsaotearoa.github.io/metagenomics_summer_school/day3/ex12_gene_prediction/#execute-prodigal

Text says we'll run prodigal in anonymous mode (`-p meta`) but the actual script has `-p single`

**Comment by mlhoggard** [comment]
Also correction for the script directly below that: 

`head -n 5 predictions/bin_0.filtered.genes.faa` needs to be corrected to `head -n 5 predictions/bin_0.genes.faa`

EDIT: same correction needed in section below this (https://genomicsaotearoa.github.io/metagenomics_summer_school/day3/ex12_gene_prediction/#strip-metadata): `head -n 5 predictions/bin_0.filtered.genes.no_metadata.faa` --> `head -n 5 predictions/bin_0.genes.no_metadata.faa`

**Comment by kmhandley** [comment]
and change `head -n 5 predictions/bin_0.filtered.genes.no_metadata.faa` to `head -n 5 predictions/bin_0.genes.no_metadata.faa`

**Comment by JSBoey** [comment]
Removed mention of "filtered"  and changed prodigal run mode.
