### ISSUE TITLE
Aragorn link not working

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#73]
https://genomicsaotearoa.github.io/metagenomics_summer_school/day3/ex12_gene_prediction/#predict-trna-and-tmrna-sequences

Aragorn link didn't work for me (unsure if it's just home connection)

**Comment by kmhandley** [comment]
Here is the working link: https://www.trna.se/

**Comment by DininduSenanayake** [comment]
Fixed in https://github.com/GenomicsAotearoa/metagenomics_summer_school/commit/6a49196b81b8bf806ad0ab9df202b87e448a9cff
