### ISSUE TITLE
6 - Vizbin

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#74]
1. Box "VizBin directory" showing loading of all_fragments.fna, states "/nesi/nobackup/nesi02659/MGSS_U/<YOUR FOLDER>/6.bin_refinement/all_bins.fna". This should be "/nesi/nobackup/nesi02659/MGSS_U/<YOUR FOLDER>/6.bin_refinement/all_fragments.fna"

2. The screenshot of the vizbin GUI all shows the wrong input file. Change to show "all_fragments.fna" or add a note in the box above (e.g. "Note the image below shows all_bins.fna instead of the all_fragments.fna file you will load").

**Comment by kmhandley** [comment]
3. VizBin box "What do scaffolds look like?". Change text from "You run follow the following code to generate input files for VizBin to visualise scaffolds." to "Run the following code to generate input files for VizBin to visualise scaffolds."

**Comment by DininduSenanayake** [comment]
Fixed in b629aacff913caf073bb061db080ea0b82352144 , 9b0f161f2424fc155bfbd8ed0a61d69a580a6043 , 712ec4003a00a649f12c5041227c660141a3f391, d9da4fa646096f67b70a5c5010b4426c2ca357af
