### ISSUE TITLE
Visualisation: ordinations

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#77]
Error running adonis:
`adonis(bray.dist ~ Group, data=map, permutations=999, method="bray")`

'adonis' will be deprecated: use 'adonis2' instead
Error in as.data.frame.default(data, optional = TRUE) : 
  cannot coerce class ‘"function"’ to a data.frame

**Comment by JSBoey** [comment]
Updated code to `adonis2(MAG_bray ~ Group, data=metadata, permutations=999)`
