### ISSUE TITLE
Can't submit host filtering index script

### ISSUE THREAD

**Issue by anniewest** [GenomicsAotearoa/metagenomics_summer_school#81]
Copied and pasted host_filt_bbmap_index script and updated folder to (and checked it worked with ls):

Working directory
cd /nesi/nobackup/ga02676/Annie/MGSS_2024/starter_files/2.fastqc/BBMask_human_reference/

Then received this message when submitting to slurm:
sbatch host_filt_bbmap_index.sl 
sbatch: error: Invalid directive found in batch script:  

The bowtie2 test script worked so not sure why this one isn't

**Comment by DininduSenanayake** [comment]
Looks like it has white spaces/invalid invisible characters (hidden non-breaking space characters) on `--partition`. One of the quickest way to verify this is to run `cat -v` against the .sl file . .i.e 

```bash
#SBATCH --partition M-BM-  M-BM-  milan
```

**Comment by DininduSenanayake** [comment]
Fixed in material https://github.com/GenomicsAotearoa/metagenomics_summer_school/commit/a19dea786a1931238a0fc832a5b079223025d13e

@JSBoey make sure to update the starter files to reflect the change
