### ISSUE TITLE
SPAdes assembly timed out

### ISSUE THREAD

**Issue by anniewest** [GenomicsAotearoa/metagenomics_summer_school#83]
9483755        spades_assembly     12    00:30:18    55:17.151     10G          TIMEOUT    
49483755.batch  batch               12    00:30:19    55:17.150         6665916K CANCELLED  
49483755.extern extern              12    00:30:18    00:00.001                0 COMPLETED

**Comment by DininduSenanayake** [comment]
this is related to "corrections"  .i.e. SPAdes has a bug which appears randomly where some assemblies get stalled at corrections. Nothing much we can do for the moment.
