### ISSUE TITLE
bin refinement vb_export files need .fa extension

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#84]
https://genomicsaotearoa.github.io/metagenomics_summer_school/day2/ex9_refining_bins/#export-contig-clusters

Need to add `.fa` extension to recommended cluster export file names for the subsequent checkM step to work.

i.e. 
> perhaps name the new cluster `mock_bin_3.cluster.fa`. If you're splitting a bin into several clusters, we recommend you name them something like `mock_bin_3.cluster_1.fa` and `mock_bin_3.cluster_2.fa`

**Comment by JSBoey** [comment]
Added file suffix
