### ISSUE TITLE
Coverage heatmap results at a glace need correcting

### ISSUE THREAD

**Issue by mlhoggard** [GenomicsAotearoa/metagenomics_summer_school#85]
https://genomicsaotearoa.github.io/metagenomics_summer_school/day4/ex16b_data_presentation_Coverage/#15-build-heatmap

"results at a glace" section is outdated compared to the latest data

E.g. 

Proteobacteria --> Pseudomonadota
only 2 MAGs recovered from this sample --> only 3 MAGs recovered from this sample
bin_8, a Nitrobacter --> bin_9, a Nitrobacter

**Comment by JSBoey** [comment]
Changed description of results
