### ISSUE TITLE
Viral taxonomy - cytoscape prep (appendix (ex11))

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#86]
`module load Singularity/3.11.3 \
MCL/14.137-gimkl-2020a \
DIAMOND/2.1.9-GCC-11.3.0`

Error message:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
There are messages associated with the following module(s):
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Singularity/3.11.3:
   Warning: Singularity is deprecated at NeSI, please switch to using Apptainer instead.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by kmhandley** [comment]
Second error message after running:

`singularity run $container/vcontact2.simg \
vcontact2_gene2genome --proteins viral_taxonomy/checkv_combined.faa \
--output viral_taxonomy/viral_genomes_g2g.csv \
-s 'Prodigal-FAA'`

ERROR:
/opt/conda/bin/vcontact2_gene2genome:174: DeprecationWarning: 'U' mode is deprecated
  with open(results.proteins, 'rU') as proteins_fh:
Traceback (most recent call last):
  File "/opt/conda/bin/vcontact2_gene2genome", line 174, in <module>
    with open(results.proteins, 'rU') as proteins_fh:
FileNotFoundError: [Errno 2] No such file or directory: 'viral_taxonomy/checkv_combined.faa'

NOTE: file exists. `ls viral_taxonomy/checkv_combined.faa`
viral_taxonomy/checkv_combined.faa

**Comment by DininduSenanayake** [comment]
>Singularity/3.11.3:
>Warning: Singularity is deprecated at NeSI, please switch to using Apptainer instead.

Fixed in https://github.com/GenomicsAotearoa/metagenomics_summer_school/commit/36ff679b812ece6e1199368bf85433a358ac4747

**Comment by JSBoey** [comment]
- Added statement to run VirSorter2 and CheckV first as per 1st virus lesson.
- Checked that changed code to Apptainer ran to completion
- Added deprecation warning statement assuring that it will run fine
